Feat/#4 create menu api
UMC-6th-BAB/BAB-BE pull request #10
Opened 2024-07-22 06:29 UTC by Cycrypto

## 연관된 이슈
> #4 [FEAT] 메뉴 api 생성 

</br>

## 작업내용
> 무엇을 개발하였는지와 기능의 코드를 설명해주세요.
메뉴엔티티 관련 API의 생성, 멀티파트파일을 이용한 이미지 업로드, 수정, 삭제 엔드포인트에 대한 매핑작업입니다.
`MenuService`의 saveImageFile이 이미지 파일 로직을 처리하는 매서드인데 아직 정확한 상의가 없어서 더미 url을 리턴하도록 작성하였습니다.

</br>

## 데이터베이스 결과

### 메뉴 생성
POST `http://localhost:8080/v1/stores/1/menus`

**요청**
``` json
{
  "menus": [
    {
      "name": "메뉴1",
      "price": 1000,
      "menuUrl": "http://example.com/menu1"
    },
    {
      "name": "메뉴2",
      "price": 2000,
      "menuUrl": "http://example.com/menu2"
    }
  ]
}

```

**응답**
```json
{
    "isSuccess": true,
    "code": "COMMON200",
    "message": "성공입니다.",
    "result": {
        "id": 17,
        "menuName": "메뉴2",
        "price": 2000,
        "menuUrl": "http://example.com/menu2",
        "store": {
            "id": 1,
            "name": null
        }
    }
}
```

### 메뉴 삭제
DELETE `http://localhost:8080/v1/stores/{store_id}/menus`

**요청**
``` json
{
  "menuIds": [6,7,8,9,10,11]
}
```

**응답**
```json
{
    "isSuccess": true,
    "code": "COMMON200",
    "message": "성공입니다."
}
```
### 메뉴 수정
PATCH `http://localhost:8080/v1/menus/{menu_id}`

**요청**
``` json
{
  "menuName": "메뉴 업데이트",
  "price": 1500,
  "menuUrl": "http://example.com/updated-menu"
}
```

**응답**
```json
{
    "isSuccess": true,
    "code": "COMMON200",
    "message": "성공입니다.",
    "result": {
        "id": 15,
        "menuName": "메뉴 업데이트",
        "price": 1500,
        "menuUrl": "http://example.com/updated-menu",
        "store": null
    }
}
```

### 메뉴 등록 (사진)
POST `http://localhost:8080/v1/menus/{menu_id}/upload-image`

**요청**

Key | Value
-- | --
imageFile | [이미지 파일 업로드]

**응답**
```json
{
    "isSuccess": true,
    "code": "COMMON200",
    "message": "성공입니다.",
    "result": {
        "id": 12,
        "menuName": "Menu13",
        "price": 1000,
        "menuUrl": "http://example.com/image",
        "store": null
    }
}
```

2024-07-22 07:03 UTC, hsuush requested changes
나중에 swagger 문서 추가 작성해주시면 좋을 거 같고 코멘트 확인해주세요!

2024-07-22 07:03 UTC, hsuush commented on src/main/java/Bob_BE/domain/menu/controller/MenuController.java
> +@RequiredArgsConstructor // @RequiredArgsConstructor 어노테이션을 추가하여 final 필드인 menuService를 생성자 주입으로 초기화합니다.
```java
@RequestMapping("/v1/menus")
```
로 작성해주시면 다른 Mapping시 중복을 피할 수 있습니다!

2024-07-22 07:03 UTC, hsuush commented on src/main/java/Bob_BE/domain/menu/controller/MenuController.java
> +    public ResponseEntity<ApiResponse<?>> createMenus(
이 부분 때문에 @RequestMapping을 다음과 같이 작성하신 거 같은데요 이런 친구는 StoreController로 옮겨가는게 맞는 거 같습니다. 이를 통해 메뉴가 어떤 가게에 속하는지 명확히 할 수 있고, 논리적인 구조를 유지할 수 있다고 합니다.

2024-07-22 07:03 UTC, hsuush commented on src/main/java/Bob_BE/domain/menu/dto/response/MenuResponseDTO.java
> +        private StoreDTO store;
어떤 것에 대한 result인지 명시해주는 것이 좋습니다. 그러므로 MenuCreateResultDto와 같이 작성해주시면 좋을 거 같습니다.

2024-07-22 07:03 UTC, hsuush commented on src/main/java/Bob_BE/domain/menu/dto/response/MenuResponseDTO.java
> +    }
다음에 Store에서 같은 dto가 필요할 경우의 중복을 줄이기 위하여 Store에 관한 dto는 StoreResponseDto로 가는 것이 좋습니다!

2024-07-22 07:03 UTC, hsuush commented on src/main/java/Bob_BE/domain/menu/service/MenuService.java
> +    }
실패로직에 대하여 작성해보자면 아래와 같이 작성할 수 있습니다. 크게 if로 묶지 않으셔도 되는거죠!

```java

Menu menu = menuRepository.findById(menuId).orElseThrow(()-> new PostHandler(ErrorStatus.MENU_NOT_FOUNT));

```
</br>

- ErrorStatus는 아래와 같이 추가해주시면 될 거 같습니다.

## ErrorStatus
//Menu
```java
USER_TYPE_NOT_VALID(HttpStatus.BAD_REQUEST, "MENU401", "해당하는 메뉴가 존재하지않습니다.."),
```

2024-07-22 07:03 UTC, hsuush commented on src/main/java/Bob_BE/domain/menu/service/MenuService.java
> +
Service 전체에 관해서 ApiResponse 자체를 반환하면 어떤 Dto가 반환되는지 Controller에서 파악이 어렵습니다. 그런 이유로 Service내에서의 리턴타입은 Dto로 하는 것이 좋습니다.

2024-07-22 07:03 UTC, hsuush commented on src/main/java/Bob_BE/domain/menu/dto/response/MenuResponseDTO.java
> +    private String menuUrl;
얘도 내부 클래스로 작성해주세요!

2024-07-22 07:03 UTC, hsuush commented on src/main/java/Bob_BE/domain/menu/service/MenuService.java
> +        }
public MenuUpdateResultDto updateMenu(){
    return Menu.builder.
                           .menu.getId()
                           .menu.getMenuName()

과 같이 dto를 반환해주어 Controller로 넘기는 것이 나중에 코드 이해하기가 좋습니다
}

2024-07-22 07:03 UTC, hsuush commented on src/main/java/Bob_BE/domain/menu/controller/MenuController.java
> +    }
함수 작성시 어떤 Dto를 명시해줄 것인가에 대한 부분도 추가해주시면 좋습니다. 이러면 Controller만 봤을 때 어떤 dto가 반환되는지 확인이 어렵기때문입니다. update로만 일단 예시를 보여드리겠습니다.
```java
public ApiResponse<MenuUpdateResultDto> 함수명 (){
    MenuUpdateResultDto menuUpdateDto = menuService.updateMenu(menuId, requestDTO);
    return ApiResponse.onSuccess(menuUpdateDto);
}
```
와 같이 작성할 수 있습니다.

2024-07-22 07:10 UTC, hsuush commented on src/main/java/Bob_BE/domain/menu/controller/MenuController.java
> +    }
코드 작성하시느라 고생 많으셨습니다!

2024-07-22 07:40 UTC, Cycrypto commented on src/main/java/Bob_BE/domain/menu/service/MenuService.java
> +    }
@hsuush  혹시 PostHandler가 UserHandler를 의미하는게 맞으실까요..?
```java
public class UserHandler extends GeneralException {

    public UserHandler(BaseErrorCode errorCode) {
        super(errorCode);
    }
}

```

2024-07-22 07:41 UTC, Cycrypto commented on src/main/java/Bob_BE/domain/menu/controller/MenuController.java
> +    public ResponseEntity<ApiResponse<?>> createMenus(
네 맞습니다..! 그러면 임의로 제 코드에서 StoreController를 생성해서 작성해야 하는데 그렇게 진행해도 괜찮을까요?

2024-07-22 07:42 UTC, Cycrypto commented on src/main/java/Bob_BE/domain/menu/dto/response/MenuResponseDTO.java
> +        private StoreDTO store;
확인했습니다 수정하겠습니다!

2024-07-22 07:44 UTC, Cycrypto commented on src/main/java/Bob_BE/domain/menu/dto/response/MenuResponseDTO.java
> +    }
이 또한 Store에 대한 파일 수정이 괜찮을지에 대한 의문때문에 저렇게 만들었었습니다. 그게 괜찮다면 Store로 옮기도록 하겠습니다 감사합니다

2024-07-22 11:00 UTC, Cycrypto commented
@hsuush 리뷰해주신 부분 수정 완료했습니다! 상세한 리뷰 감사합니다!

2024-07-22 11:28 UTC, hsuush approved these changes
ㅎㅎ고생하셨습니다 코멘트 한번만(아마 마지막...ㅎㅎ) 확인해주시면 될 거 같습니다. 고생많으셨습니다.

2024-07-22 11:28 UTC, hsuush commented on src/main/java/Bob_BE/domain/menu/service/MenuService.java
> +    }
dto명도 잘 변경해주셨고 반환타입도 잘 되어있네요 좋습니다!

2024-07-22 11:28 UTC, hsuush commented on src/main/java/Bob_BE/domain/menu/service/MenuService.java
> +                    .orElseThrow(() -> new UserHandler(ErrorStatus.MENU_NOT_FOUND));
아 필요한 핸들러는 작성해주시면 돼요. 유저핸들러와 같이 MenuHandler를 GeneralException을 상속받아주시면 됩니다.

2024-07-22 11:28 UTC, hsuush commented on src/main/java/Bob_BE/domain/menu/controller/MenuController.java
> +    }
ResponseEntity도 빼주셔도 됩니다!

2024-07-22 11:30 UTC, hsuush commented on src/main/java/Bob_BE/domain/menu/service/MenuService.java
> +    }
보통 이렇게 빌더를 쓰는 부분을 따로 Converter로 빼곤 합니다. 서비스는 서비스 로직이 주된 부분이라 그렇습니다ㅎㅎ

2024-07-23 02:00 UTC, Cycrypto commented
2차 피드백 반영완료하였습니다 리뷰 감사합니다

2024-07-23 11:06 UTC, iseevict approved these changes
LGTM

2024-07-23 11:48 UTC, KimChungEon commented
회의에서 말한대로 DTO 클래스명 Dto로 수정해주시면 될 것 같습니다.

2024-07-24 02:31 UTC, wonjun0120 requested changes
코멘트 확인 부탁드립니다

2024-07-24 02:31 UTC, wonjun0120 commented on src/main/java/Bob_BE/domain/menu/controller/MenuController.java
swagger부분 추가 부탁드립니다

2024-07-24 02:31 UTC, wonjun0120 commented on src/main/resources/application.yml
dev브랜치와 conflict가 있다고 합니다
확인 부탁드립니다.

2024-07-24 05:17 UTC, Cycrypto commented on src/main/resources/application.yml
해당 부분 데이터베이스 비밀번호 부분으로, 추후 merge 할 때 해결해서 머지하도록 하겠습니다.

2024-07-24 07:22 UTC, wonjun0120 commented on src/main/java/Bob_BE/domain/menu/converter/MenuConverter.java
> +    private MenuConverter() {}
이 부분은 생성자인가요?
저희 롬복 사용하는만큼 `@NoArgsConstructor`사용하면 될 것 같습니다.

2024-07-25 04:30 UTC, KimChungEon approved these changes

2024-07-25 04:58 UTC, merged