[Feat][학생 소셜 로그인, 회원가입 기능]
UMC-6th-BAB/BAB-BE pull request #5
Opened 2024-07-21 04:25 UTC by wonjun0120

## 연관된 이슈
> close #3 

</br>

## 작업내용
> 학생 회원가입, 로그인 기능 구현
카카오 소셜 로그인 연동
DB에 학생의 정보가 없는 경우 회원가입 자동 진행 및 로그인,
DB에 학생의 정보가 있는 경우 로그인 진행

</br>

2024-07-21 06:35 UTC, iseevict approved these changes
LGTM

2024-07-21 12:23 UTC, hsuush requested changes
이렇게 작성하시면 더 좋을 거 같습니다! 이렇게 다같이 진행해도 좋을 거 같아요!

2024-07-21 12:23 UTC, hsuush commented on src/main/java/Bob_BE/domain/student/dto/request/StudentRequestDto.java
> +    }
변수들은 외부에서 접근하지 못하도록 private으로 선언하는 것을 추천드립니다!
그러면 접근시 위에 사용하신 @Getter로 접근하게됩니다ㅎㅎ
```java
@NotNull
private String token;
```
아래 Dto도 동일한 코멘트입니다.

2024-07-21 12:23 UTC, hsuush commented on src/main/java/Bob_BE/domain/student/controller/StudentController.java
> +        return new ResponseEntity<>(apiResponse, response.getSuccessStatus().getHttpStatus());
저는 ApiResponse를 아래와 같이 작성하는 편입니다! 이러면  코드수도 줄고 가독성이 좋아져요ㅎㅎ
```java
public ApiResponse<StudentRequestDto.LoginOrRegisterDto> 함수명(매개변수명){
    StudentResponseDto.LoginOrRegisterDto loginDto= studentService.registerOrLogin(request);
    return ApiResponse.onSuccess(loginDto);
}
```
왠만한 예외는 저희가 던져주고 ApiResponse에선 try-catch와 같은 에러도 인식해줘서 이렇게 작성해줘도 됩니다. 반환값도 잘 나올거예요

```json
{
  "isSuccess": true,
  "code": "COMMON200",
  "message": "성공입니다.",
  "result": {
	  "jwt" : "String"
  }
}
```

2024-07-21 12:23 UTC, hsuush commented on src/main/java/Bob_BE/domain/student/dto/response/StudentResponseDto.java
> +    }
Controller와 같이 작성하면 Dto 이렇게 작성하셔도 됩니다!
```java
@Getter
@Builder
public static class LoginOrRegisterDto{
    private String jwt;
}
```

2024-07-22 01:36 UTC, wonjun0120 commented on src/main/java/Bob_BE/domain/student/controller/StudentController.java
> +        return new ResponseEntity<>(apiResponse, response.getSuccessStatus().getHttpStatus());
처음에는 저렇게 작성했었으나 회원가입과 로그인의 경우 응답코드를 달리해주는게 불가능하여 현재코드처럼 작성하였습니다.
```java
public ApiResponse<StudentRequestDto.LoginOrRegisterDto> 함수명(매개변수명){
    StudentResponseDto.LoginOrRegisterDto loginDto= studentService.registerOrLogin(request);
    return ApiResponse.onSuccess(loginDto);
}
```
처럼 작성하면 회원가입이나, 로그인 상관없이 200코드만 반환이되고
`return ApiResponse.of`를 통해 201코드를 반환하려해도 200으로 반환되더라구요

혹시 `return ApiResponse.of`만을 사용하면서 http 응답코드를 변경시키는 방법이 있을까요?

2024-07-22 01:48 UTC, wonjun0120 commented on src/main/java/Bob_BE/global/swagger/SwaggerConfig.java
config 파일들을 하나의 config 폴더에 생성하지 않고, 분리한 이유가 있을까요?
@iseevict

2024-07-22 02:15 UTC, iseevict commented on src/main/java/Bob_BE/global/swagger/SwaggerConfig.java
원래는 하나의 config 폴더에 넣어두는 편인데 dto 폴더에서 request, response 구분하는 것으로 봤을 때 잘게 쪼개서 구분해주는게 일관성 있을 것 같아 이렇게 진행했습니다.

2024-07-22 02:19 UTC, hsuush commented on src/main/java/Bob_BE/domain/student/controller/StudentController.java
> +        return new ResponseEntity<>(apiResponse, response.getSuccessStatus().getHttpStatus());
로그인은 분기가 나누어진다는 점을 제가 간과한 거 같습니다.

확인결과 200코드가 반환되는 이유는 워크북에서 가져온 해당 성공을 생성하는 부분에서 COMMON200만 반환하도록 설정되어있네요. 저 또한 예전 프로젝트 진행시 모든 응답은 200으로 달라는 프론트의 이야기가 있었어서 그대로 사용했던 거 같습니다. 

</br>

##ApiResponse파일 중 일부

- 수정전 : 모두 200의 응답을 내보내도록 설정되어있음.
- 
```java
// 성공한 경우 응답 생성
    public static <T> ApiResponse<T> onSuccess(T result){
        return new ApiResponse<>(true, SuccessStatus._OK.getCode() , SuccessStatus._OK.getMessage(), result);
    }
```

</br>

- 수정후 : 설정한 SuccessStatus를 반환하도록 설정되어있음

```java
// 성공한 경우 응답 생성
    public static <T> ApiResponse<T> onSuccess(SuccessStatus status, T result){
        return new ApiResponse<>(true, status.getCode() , status.getMessage(), result);
    }
```

</br>

## StudentResponseDto
그러면 SuccessStatus를 넣어보는게 나을 거 같긴하네요. get 함수는 따로 추가하지 않으셔도 될 겁니다. @Getter 어노테이션이 있어서.

</br>

## StudentController
```java
    @PostMapping
    public ApiResponse<StudentResponseDto.LoginOrRegisterDto> registerOrLoginStudent(@RequestBody StudentRequestDto.LoginOrRegisterDto request){
        StudentResponseDto.LoginOrRegisterDto response = studentService.registerOrLogin(request);

        return ApiResponse.onSuccess(response.getSuccessStatus(), response);
    }
```

다음과 같이 바꿔보면 어떨까 싶어요!

로컬에서 변경해보았는데 제가 토큰이 없어 직접 실행해보지 못한 바 죄송합니다. 혹시 문제 생기시면 말씀주세요!

2024-07-22 02:40 UTC, wonjun0120 commented on src/main/java/Bob_BE/domain/student/controller/StudentController.java
> +        return new ResponseEntity<>(apiResponse, response.getSuccessStatus().getHttpStatus());
```java
public ApiResponse<?> registerOrLoginStudent(@RequestBody StudentRequestDto.LoginOrRegisterDto request){
        StudentResponseDto.LoginOrRegisterDto response = studentService.registerOrLogin(request);

        return ApiResponse.of(response.getSuccessStatus(), response);
    }
```

이 형태로도 사용해봤었지만 여전히 200응답만 전송되었었습니다.
이번에 다시 확인해봐도 여전하더라구요..

2024-07-22 03:28 UTC, wonjun0120 commented on src/main/java/Bob_BE/global/swagger/SwaggerConfig.java
@hsuush 어떻게 생각하시는지 궁금합니다.
하나의 config 폴더로 관리할 것인지 아니면 config파일을 각 의존성별로 관리할 것인지 궁금합니다.

저는 config폴더 하나로 관리하는 것이 좋아보입니다.

2024-07-22 03:51 UTC, hsuush reviewed
수고하셨습니다.

2024-07-22 03:51 UTC, hsuush commented on src/main/java/Bob_BE/domain/student/controller/StudentController.java
> +                    "<br>kakao developer에서 예시 token을 받아올 수 있습니다.")
예전에 프론트분들께 들은 바로는 description에 어떤 dto가  반환되는지 써주면 좋다고하시더라구요!

2024-07-22 03:51 UTC, hsuush commented on src/main/java/Bob_BE/domain/student/controller/StudentController.java
> +            @io.swagger.v3.oas.annotations.responses.ApiResponse(responseCode = "500", description = "GLOBAL401: 서버 에러")})
응답 잘 작성해주셨네요. 좋습니다.

2024-07-22 03:51 UTC, hsuush commented on src/main/java/Bob_BE/domain/student/dto/response/StudentResponseDto.java
> +        }
@Getter 어노테이션이 존재하여 해당 함수는 없어도 될 거 같습니다!

2024-07-22 03:52 UTC, hsuush approved these changes
고생하셨습니다!

2024-07-22 03:53 UTC, hsuush commented on src/main/java/Bob_BE/global/swagger/SwaggerConfig.java
제가 폴더 구조를 세세하게 짜서 이런 문제가 발생했나보군요.. 저도 하나의 Config 폴더로 진행하는 것이 맞다고 생각합니다. 혼란을 드려 죄송합니다!

2024-07-22 04:09 UTC, iseevict commented
확인했습니다. 고생하셨습니다 😄

2024-07-23 11:12 UTC, KimChungEon commented
LGTM

2024-07-23 11:13 UTC, merged